### ISSUE TITLE
fake controller

### ISSUE THREAD

**Issue by mzillich** [squirrel-project/squirrel_robotino#167]
I was wondering, why this is started in `roslaunch robotino_bringup tuw-robotino2.launch`

> [ INFO] [1484738572.700930431]: Fake controller 'fake_robotino_controller' with joints [ base_jointx base_jointy base_jointz arm_joint1 arm_joint2 arm_joint3 arm_joint4 arm_joint5 ]

**Comment by ipa-nhg** [comment]
To be honest, I have no idea who is doing that, could you please check it? 
using the rqt_console you can see which node is publishing the message

**Comment by mzillich** [comment]
node is `/move_group`

**Comment by ipa-nhg** [comment]
thanks 

this is Moveit! https://github.com/squirrel-project/squirrel_manipulation/blob/indigo_dev/tuw_moveit_config/config/fake_controllers.yaml,  maybe @lokalmatador knows why is it needed, any clue?

**Comment by mzillich** [comment]
@lokalmatador do you know (or Simon Haller - what is his github id btw?) what these fake controllers do? They can be disabled with `false` in
https://github.com/squirrel-project/squirrel_manipulation/blob/indigo_dev/tuw_moveit_config/launch/demo.launch#L15
Shouldn't they be disabled? We have real controllers.

**Comment by mzillich** [comment]
@lokalmatador I see that in `uibk_moveit_config_sh` you have a `moveit_planning.launch`, which `tuw_moveit_config` does not have. I assume that calling `demo.launch` (in JB's account) was a copy/paste leftover.

**Comment by ghost** [comment]
Hi,

to answer your first question on Simon's github id, it's @smhaller. 

Now, your second question: that fake_controllers.yaml file is automatically generated by moveit's setup assistant. I just checked UIBK moveit config (sh), the file is there, but only referenced from inside the "fake_moveit_controller_manager.launch.xml" launch file template. So this thing is never loaded - I think it'd even throw errors as it ends with .xml. Anyways, just ignore it, its a auto generated artifact in case you do not connect moveit to a real robot.

Now, last but not least the third question regarding that file: yeah, that's an artifacts from copy/paste. Just start demo.launch, that should also be fine (which is also what we do currently). We created that file to launch moveit without rviz (though commenting it out would've been enough, but hey, we choose the easy way....).

I think that answers everything, otherwise, mention me again and you'll get more answers.

Best,

Philipp
